package org.example.entity;

public enum FraudFlagger {
    HIGH_AMOUNT_TRANSACTION,
    ODD_TIME_TRANSACTION,
    TOO_MANY_TRANSACTION_ACROSS_MERCHANT,
    TOO_MANY_TRANSACTION_WITH_SAME_MERCHANT,
    FRAUDULENT_MERCHANT
}
